"""
Email sender utility for the Research Agent CLI.

Supports multiple email backends via environment variables.

SMTP Mode (Gmail, custom SMTP, etc.):
  EMAIL_BACKEND=smtp
  SMTP_HOST        (default: smtp.gmail.com)
  SMTP_PORT        (default: 587)
  SMTP_USER        sender account
  SMTP_PASSWORD    password or app-password
  SMTP_FROM_NAME   display name  (default: Research Agent)

SendGrid Mode (RECOMMENDED - free up to 100 emails/day):
  EMAIL_BACKEND=sendgrid
  SENDGRID_API_KEY your_sendgrid_api_key_here
  SENDGRID_FROM_EMAIL your_verified_sender@domain.com

Usage:
    from utils.email_sender import send_report_email
    ok, msg = send_report_email(to_email, subject, report_text, html_body)
"""

import os
import smtplib
import textwrap
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from datetime import datetime
from typing import Optional, Tuple


# ── Get email backend (sendgrid or smtp) ─────────────────────────────────────
def _get_backend() -> str:
    backend = os.getenv("EMAIL_BACKEND", "smtp").lower()
    return backend if backend in ("smtp", "sendgrid") else "smtp"


# ── SMTP config from environment ─────────────────────────────────────────────
def _smtp_config() -> dict:
    return {
        "host":      os.getenv("SMTP_HOST",      "smtp.gmail.com"),
        "port":      int(os.getenv("SMTP_PORT",  "587")),
        "user":      os.getenv("SMTP_USER",      ""),
        "password":  os.getenv("SMTP_PASSWORD",  ""),
        "from_name": os.getenv("SMTP_FROM_NAME", "Research Agent"),
    }


# ── SendGrid config ──────────────────────────────────────────────────────────
def _sendgrid_config() -> dict:
    return {
        "api_key":     os.getenv("SENDGRID_API_KEY", ""),
        "from_email":  os.getenv("SENDGRID_FROM_EMAIL", "noreply@researchagent.local"),
        "from_name":   os.getenv("SENDGRID_FROM_NAME", "Research Agent"),
    }


# ── HTML template ─────────────────────────────────────────────────────────────
def _build_html(subject: str, sections: list[dict]) -> str:
    """
    sections = [{"heading": str, "body": str, "is_table": bool, "rows": list}]
    """
    rows_html = ""
    for sec in sections:
        heading = sec.get("heading", "")
        body    = sec.get("body", "")
        is_table = sec.get("is_table", False)
        rows     = sec.get("rows", [])   # list of dicts with same keys

        rows_html += f"""
        <h2 style="color:#1a3a5c;border-bottom:2px solid #1a3a5c;
                   padding-bottom:4px;margin-top:32px">{heading}</h2>
        """

        if is_table and rows:
            headers = list(rows[0].keys())
            th = "".join(
                f"<th style='background:#1a3a5c;color:#fff;padding:8px 12px;"
                f"text-align:left'>{h}</th>" for h in headers
            )
            trs = ""
            for i, row in enumerate(rows):
                bg = "#f0f4f8" if i % 2 == 0 else "#ffffff"
                tds = "".join(
                    f"<td style='padding:7px 12px;border-bottom:1px solid #dde'>"
                    f"{row.get(h,'')}</td>" for h in headers
                )
                trs += f"<tr style='background:{bg}'>{tds}</tr>"
            rows_html += f"""
            <table style="width:100%;border-collapse:collapse;margin-top:12px">
              <thead><tr>{th}</tr></thead>
              <tbody>{trs}</tbody>
            </table>"""
        else:
            # Render body as paragraphs
            for para in (body or "").split("\n"):
                para = para.strip()
                if para:
                    rows_html += (
                        f"<p style='margin:6px 0;line-height:1.7;"
                        f"color:#333'>{para}</p>"
                    )

    return f"""<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><title>{subject}</title></head>
<body style="font-family:Arial,sans-serif;max-width:860px;margin:0 auto;
             padding:24px;color:#222">
  <div style="background:#1a3a5c;color:#fff;padding:20px 28px;
              border-radius:8px 8px 0 0">
    <h1 style="margin:0;font-size:22px">🔬 Research Agent Report</h1>
    <p style="margin:6px 0 0;opacity:.8;font-size:13px">{subject}</p>
  </div>
  <div style="background:#fff;padding:24px 28px;border:1px solid #dde;
              border-top:none;border-radius:0 0 8px 8px">
    {rows_html}
    <hr style="border:none;border-top:1px solid #eee;margin-top:40px">
    <p style="font-size:11px;color:#999;text-align:center;margin-top:8px">
      Generated by Research Agent · {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}
    </p>
  </div>
</body>
</html>"""


def build_report_sections(final_report: dict, state: dict) -> list[dict]:
    """Convert final_report + state into HTML section list."""
    sections = []

    # Executive Summary
    sections.append({
        "heading": "Executive Summary",
        "body": final_report.get("executive_summary", "Not available."),
    })

    # Detailed Sections
    for sec in final_report.get("sections", []):
        sections.append({
            "heading": sec.get("heading", "Section"),
            "body": sec.get("content", ""),
        })

    # Hypotheses table
    hvs = final_report.get("hypotheses_verdict", [])
    if hvs:
        sections.append({
            "heading": "Hypotheses & Verdicts",
            "is_table": True,
            "rows": [
                {
                    "ID":        h.get("id", ""),
                    "Hypothesis": h.get("statement", ""),
                    "Verdict":   h.get("verdict", "").upper(),
                    "Summary":   h.get("summary", ""),
                }
                for h in hvs
            ],
        })

    # Key Conclusions
    conclusions = final_report.get("key_conclusions", [])
    if conclusions:
        body = "\n".join(f"{i+1}. {c}" for i, c in enumerate(conclusions))
        sections.append({"heading": "Key Conclusions", "body": body})

    # Contradictions table
    cflagged = final_report.get("contradictions_flagged", [])
    if cflagged:
        sections.append({
            "heading": "Contradictions Detected",
            "is_table": True,
            "rows": [
                {
                    "Severity": c.get("severity", "").upper(),
                    "Summary":  c.get("summary", ""),
                    "Action":   c.get("action", ""),
                }
                for c in cflagged
            ],
        })

    # Research Gaps
    gaps = final_report.get("research_gaps", [])
    if gaps:
        body = "\n".join(f"• {g}" for g in gaps)
        sections.append({"heading": "Research Gaps", "body": body})

    # Follow-up Recommendations
    fuqs = final_report.get("follow_up_questions", [])
    if fuqs:
        body = "\n".join(f"{i+1}. {q}" for i, q in enumerate(fuqs))
        sections.append({"heading": "Follow-up Recommendations", "body": body})

    # Sources / Citations
    cites = final_report.get("citations", [])
    if cites:
        sections.append({
            "heading": "Sources & Citations",
            "is_table": True,
            "rows": [
                {
                    "#":       str(i + 1),
                    "Title":   c.get("title", ""),
                    "Authors": c.get("authors", ""),
                    "Year":    str(c.get("year", "")),
                    "DOI/URL": c.get("doi") or c.get("url") or "",
                }
                for i, c in enumerate(cites)
            ],
        })

    # Confidence score
    conf = final_report.get("confidence_overall", 0.0)
    sections.append({
        "heading": "Confidence Score",
        "body": f"Overall Confidence: {int(conf * 100)}%\n\n"
                "This score reflects the quality, relevance, and consensus "
                "level of the retrieved evidence.",
    })

    return sections


def build_plaintext(final_report: dict) -> str:
    """Fallback plain-text version of the full report."""
    lines = []
    sep  = "=" * 72
    sep2 = "-" * 72

    def add(heading, body=""):
        lines.append(f"\n{sep}\n{heading.upper()}\n{sep}")
        if body:
            for para in textwrap.wrap(str(body), width=70):
                lines.append(para)

    add("Executive Summary", final_report.get("executive_summary", "N/A"))

    for sec in final_report.get("sections", []):
        add(sec.get("heading", "Section"), sec.get("content", ""))

    # Hypotheses table
    hvs = final_report.get("hypotheses_verdict", [])
    if hvs:
        lines.append(f"\n{sep}\nHYPOTHESES & VERDICTS\n{sep}")
        lines.append(f"{'ID':<8} {'VERDICT':<16} {'STATEMENT'}")
        lines.append(sep2)
        for h in hvs:
            lines.append(
                f"{h.get('id',''):<8} {h.get('verdict','').upper():<16} "
                f"{h.get('statement','')[:55]}"
            )

    # Key Conclusions
    conc = final_report.get("key_conclusions", [])
    if conc:
        add("Key Conclusions", "\n".join(f"{i+1}. {c}" for i, c in enumerate(conc)))

    # Contradictions
    cf = final_report.get("contradictions_flagged", [])
    if cf:
        lines.append(f"\n{sep}\nCONTRADICTIONS\n{sep}")
        for c in cf:
            lines.append(
                f"[{c.get('severity','').upper()}] {c.get('summary','')}"
            )
            lines.append(f"  → Action: {c.get('action','')}")

    # Research Gaps
    gaps = final_report.get("research_gaps", [])
    if gaps:
        add("Research Gaps", "\n".join(f"• {g}" for g in gaps))

    # Follow-up Recommendations
    fuqs = final_report.get("follow_up_questions", [])
    if fuqs:
        add("Follow-up Recommendations",
            "\n".join(f"{i+1}. {q}" for i, q in enumerate(fuqs)))

    # Sources
    cites = final_report.get("citations", [])
    if cites:
        lines.append(f"\n{sep}\nSOURCES & CITATIONS\n{sep}")
        for i, c in enumerate(cites):
            lines.append(
                f"{i+1:>3}. {c.get('title','Untitled')[:65]}"
            )
            lines.append(
                f"      Authors : {c.get('authors','N/A')[:60]}"
            )
            lines.append(
                f"      Year    : {c.get('year','')}"
            )
            lines.append(
                f"      DOI/URL : {c.get('doi') or c.get('url','N/A')}"
            )

    conf = final_report.get("confidence_overall", 0.0)
    add("Confidence Score", f"Overall Confidence: {int(conf * 100)}%")

    lines.append(f"\n{sep}\n")
    return "\n".join(lines)


def send_report_email(
    to_email: str,
    subject: str,
    final_report: dict,
    state: dict,
) -> Tuple[bool, str]:
    """
    Send the research report to to_email.
    Returns (success: bool, message: str).
    
    Uses backend specified in EMAIL_BACKEND (sendgrid or smtp).
    """
    backend = _get_backend()
    
    if backend == "sendgrid":
        return _send_via_sendgrid(to_email, subject, final_report, state)
    else:
        return _send_via_smtp(to_email, subject, final_report, state)


def _send_via_smtp(
    to_email: str,
    subject: str,
    final_report: dict,
    state: dict,
) -> Tuple[bool, str]:
    """Send via SMTP (Gmail, Outlook, custom servers, etc.)"""
    cfg = _smtp_config()
    if not cfg["user"] or not cfg["password"]:
        return False, (
            "SMTP credentials not set. "
            "Export SMTP_USER and SMTP_PASSWORD environment variables, "
            "or use EMAIL_BACKEND=sendgrid with SENDGRID_API_KEY."
        )

    # Build parts
    sections  = build_report_sections(final_report, state)
    html_body = _build_html(subject, sections)
    plain     = build_plaintext(final_report)

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"]    = f"{cfg['from_name']} <{cfg['user']}>"
    msg["To"]      = to_email
    msg.attach(MIMEText(plain,     "plain", "utf-8"))
    msg.attach(MIMEText(html_body, "html",  "utf-8"))

    try:
        with smtplib.SMTP(cfg["host"], cfg["port"], timeout=30) as server:
            server.ehlo()
            server.starttls()
            server.login(cfg["user"], cfg["password"])
            server.sendmail(cfg["user"], [to_email], msg.as_string())
        return True, f"Report sent successfully to {to_email}"
    except smtplib.SMTPAuthenticationError:
        return False, (
            "SMTP authentication failed. "
            "Check SMTP_USER / SMTP_PASSWORD (use an App Password for Gmail), "
            "or switch to EMAIL_BACKEND=sendgrid with SENDGRID_API_KEY."
        )
    except Exception as e:
        return False, f"Failed to send email: {e}"


def _send_via_sendgrid(
    to_email: str,
    subject: str,
    final_report: dict,
    state: dict,
) -> Tuple[bool, str]:
    """Send via SendGrid API (recommended - free up to 100 emails/day)"""
    cfg = _sendgrid_config()
    if not cfg["api_key"]:
        return False, (
            "SendGrid API key not set. "
            "Export SENDGRID_API_KEY environment variable, "
            "or use EMAIL_BACKEND=smtp with SMTP_USER / SMTP_PASSWORD."
        )

    try:
        import requests
    except ImportError:
        return False, "requests library not installed. Run: pip install requests"

    # Build email parts
    sections  = build_report_sections(final_report, state)
    html_body = _build_html(subject, sections)
    plain     = build_plaintext(final_report)

    payload = {
        "personalizations": [
            {
                "to": [{"email": to_email}],
                "subject": subject,
            }
        ],
        "from": {
            "email": cfg["from_email"],
            "name": cfg["from_name"],
        },
        "content": [
            {"type": "text/plain", "value": plain},
            {"type": "text/html",  "value": html_body},
        ],
    }

    headers = {
        "Authorization": f"Bearer {cfg['api_key']}",
        "Content-Type": "application/json",
    }

    try:
        resp = requests.post(
            "https://api.sendgrid.com/v3/mail/send",
            json=payload,
            headers=headers,
            timeout=30,
        )
        if resp.status_code in (200, 202):
            return True, f"Report sent successfully to {to_email} (via SendGrid)"
        else:
            return False, (
                f"SendGrid error {resp.status_code}: {resp.text[:200]}"
            )
    except Exception as e:
        return False, f"Failed to send via SendGrid: {e}"
